# Meta data
name:             Example42
authors:          flathemes
description:      Example42 Puppet Services. Training, moduls development, infrastructures migration, architecture design.

# Dependencies
pygments:         true

# Permalinks
permalink:        pretty

# Server
# source:           /
#url:              http://example42.github.io
#encoding:         UTF-8

# Custom vars
current_version:  2.0.1
repo:             https://github.com/bootflat/bootflat.github.io

markdown: kramdown
